### ISSUE TITLE
Cannot set mouse raw input

### ISSUE THREAD

**Issue by OlliC** [ValveSoftware/portal2#98]
If i activate the mouse raw input, it disables itself again when i go back to the menu.

**Comment by OlliC** [comment]
```
Prozessor:
    Hersteller: GenuineIntel
    CPU-Familie: 0x6
    CPU-Modell: 0x2a
    CPU-Stepping: 0x7
    CPU-Typ: 0x0
    Geschwindigkeit: 3401 MHz
    8 logische Prozessoren
    4 technische Prozessoren
    HyperThreading:  Unterstützt
    FCMOV:  Unterstützt
    SSE2:  Unterstützt
    SSE3:  Unterstützt
    SSSE3:  Unterstützt
    SSE4a:  Nicht unterstützt
    SSE41:  Unterstützt
    SSE42:  Unterstützt

Netzwerk-Informationen:
    Netzwerk-Geschwindigkeit: 

Betriebssystem:
    Debian GNU/Linux 7.4 (wheezy) (64 Bit)
    Kernel-Name: Linux
    Kernel-Version: 3.2.0-4-amd64
    X-Server-Vendor: The X.Org Foundation
    X-Server-Release: 11204000
    X-Fenstermanager: Mutter
    Steam-Runtime-Version: steam-runtime-release_2014-02-05

Grafikkarte:
    Treiber: NVIDIA Corporation GeForce GTX 660/PCIe/SSE2

    Treiberversion: 4.2.0 NVIDIA 304.88
    OpenGL-Version: 4.2
    Desktop-Farbtiefe: 24 Bit per Pixel
    Monitor-Aktualisierungsrate: 60 Hz
    Anbieterkennung: 0x10de
    Gerätekennung: 0x11c0
    Anzahl der Monitore: 1
    Anzahl der logischen Grafikkarten: 1
    Prim. Anzeigeauflösung: 1920 x 1080
    Desktopauflösung: 1920 x 1080
    Prim. Anzeigegröße: 50.9 cm x 28.6 cm (58.3 cm diag.)

    Primärer Bus: PCI Express 16x
    Primärer VRAM: 2048 MB
    Unterstützte MSAA-Modi: 2x 4x 8x 16x 

Soundkarte:
    Audiogerät: IDT 92HD89E2

Speicher:
    RAM: 5968 MB

Weitere Daten:
    UI-Sprache: Deutsch (Deutsch)
    SPRACHE: de_DE.UTF-8
    Mikrofon: Not set
    Verfügbarer Festplattenspeicher insgesamt: 457392 MB
    Größter freier Festplattenspeicherblock: 270981 MB

Installierte Software:

Neueste Fehlerberichte:
```
